$(function(){
  $("div").click(function(){
    $("div").removeClass();
    $("p").hide();
    $(this).find("p").show();
    $(this).toggleClass("card");
    $(this).click(function(){
      $(this).find("p").toggle();
      $(this).toggleClass("card");
    });
  });
});
